//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abteilungen
    {
        public Abteilungen()
        {
            this.Fahrzeuge = new HashSet<Fahrzeuge>();
            this.Nutzer = new HashSet<Nutzer>();
        }
    
        public int abteilungID { get; set; }
        public string abteilung { get; set; }
        public int firmaID { get; set; }
        public string abteilungbeschr { get; set; }
    
        public virtual Firmen Firmen { get; set; }
        public virtual ICollection<Fahrzeuge> Fahrzeuge { get; set; }
        public virtual ICollection<Nutzer> Nutzer { get; set; }
    }
}
