//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Betriebssysteme
    {
        public Betriebssysteme()
        {
            this.Geraete = new HashSet<Geraete>();
        }
    
        public int betriebssysID { get; set; }
        public string betriebssys { get; set; }
        public string betriebssysbeschr { get; set; }
    
        public virtual ICollection<Geraete> Geraete { get; set; }
    }
}
