//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridTest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataGridTestEntities : DbContext
    {
        public DataGridTestEntities()
            : base("name=DataGridTestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Abteilungen> Abteilungen { get; set; }
        public DbSet<Betriebssysteme> Betriebssysteme { get; set; }
        public DbSet<Fahrzeuge> Fahrzeuge { get; set; }
        public DbSet<Firmen> Firmen { get; set; }
        public DbSet<Geraete> Geraete { get; set; }
        public DbSet<Geraetehersteller> Geraetehersteller { get; set; }
        public DbSet<Geraetemodelle> Geraetemodelle { get; set; }
        public DbSet<Geraetetypen> Geraetetypen { get; set; }
        public DbSet<Netze> Netze { get; set; }
        public DbSet<Nutzer> Nutzer { get; set; }
        public DbSet<Provider> Provider { get; set; }
        public DbSet<Simgroessen> Simgroessen { get; set; }
        public DbSet<Simkarten> Simkarten { get; set; }
        public DbSet<Simnutzung> Simnutzung { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Tarife> Tarife { get; set; }
        public DbSet<Tarifoptionen> Tarifoptionen { get; set; }
        public DbSet<Telefonnummern> Telefonnummern { get; set; }
        public DbSet<Verbrauch> Verbrauch { get; set; }
        public DbSet<Verkaeufer> Verkaeufer { get; set; }
        public DbSet<Vertraege> Vertraege { get; set; }
        public DbSet<Vertragsarten> Vertragsarten { get; set; }
    }
}
