//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fahrzeuge
    {
        public Fahrzeuge()
        {
            this.Simnutzung = new HashSet<Simnutzung>();
        }
    
        public int fahrzeugID { get; set; }
        public string fahrzeugkennzeichen { get; set; }
        public string fahrzeugmodell { get; set; }
        public Nullable<int> abteilungID { get; set; }
        public string fahrzeugnotiz { get; set; }
    
        public virtual Abteilungen Abteilungen { get; set; }
        public virtual ICollection<Simnutzung> Simnutzung { get; set; }
    }
}
