//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Netze
    {
        public Netze()
        {
            this.Telefonnummern = new HashSet<Telefonnummern>();
        }
    
        public int netzID { get; set; }
        public string netzname { get; set; }
        public string netzbeschr { get; set; }
    
        public virtual ICollection<Telefonnummern> Telefonnummern { get; set; }
    }
}
