//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Simgroessen
    {
        public Simgroessen()
        {
            this.Geraete = new HashSet<Geraete>();
            this.Simkarten = new HashSet<Simkarten>();
        }
    
        public int simgroesseID { get; set; }
        public string simgroesse { get; set; }
        public string simgroessebeschr { get; set; }
    
        public virtual ICollection<Geraete> Geraete { get; set; }
        public virtual ICollection<Simkarten> Simkarten { get; set; }
    }
}
