//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarifoptionen
    {
        public Tarifoptionen()
        {
            this.Vertraege = new HashSet<Vertraege>();
            this.Vertraege1 = new HashSet<Vertraege>();
            this.Vertraege2 = new HashSet<Vertraege>();
        }
    
        public int tarifoptionID { get; set; }
        public string tarifoptionname { get; set; }
        public string tarifoptionbeschr { get; set; }
    
        public virtual ICollection<Vertraege> Vertraege { get; set; }
        public virtual ICollection<Vertraege> Vertraege1 { get; set; }
        public virtual ICollection<Vertraege> Vertraege2 { get; set; }
    }
}
