//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vertragsarten
    {
        public Vertragsarten()
        {
            this.Vertraege = new HashSet<Vertraege>();
        }
    
        public int vertragsartID { get; set; }
        public string vertragsart { get; set; }
        public string vertragsartbeschr { get; set; }
    
        public virtual ICollection<Vertraege> Vertraege { get; set; }
    }
}
